### ISSUE TITLE
Default Use Fix

### ISSUE THREAD

**Issue by Teque5** [qaptadrone/gcp_aruco_generator#2]
- Current implementation doesn't produce any output in the svg with no arguments. Specifically you have to add `-b` to produce valid output. Maybe remove this switch.
- set marker generator as executable
- first line should be `#!/usr/bin/env python3` to run on any system
- Dictionaries up to 5X5 work for me. 6X6 and 7X7 get this error:
```
Total marker size is going to be 600mm
Ground Sampling Distance is a maximum of 10.4mm/pixels, fly accordingly
Your marker has been created and is available here ./6X6_100_0.svg .
Traceback (most recent call last):
  File "./marker_generator.py", line 699, in <module>
    generate_marker(marker_id)
  File "./marker_generator.py", line 382, in generate_marker
    svg.add(createPixels(svg, bits, datawidth, border, margin, white_color))
  File "./marker_generator.py", line 287, in createPixels
    if not border or bits[i * datawidth + j]:
IndexError: list index out of range
```
- Dictionary arg should call 'upper' so that using "5x5_100" and "5X5_100" both work.

**Comment by gromain** [comment]
Hey,

I didn't see your comment before. Thanks for your input, I'll keep this open and integrate a fix for your suggestions.

I suspect there is an issue with the availability of the 7x7 and 6x6 dictionaries, I'll dig into this.

**Comment by gromain** [comment]
Thanks for your feedback.

The '-b' flag absence was producing unusable output indeed. I removed it since the black border around the marker is part of the standard anyway.

I've fixed the rest of the issues.

**Comment by Teque5** [comment]
Remember to remove references to `-b` from your `README.md`.

I also created this [vhs](https://github.com/charmbracelet/vhs/tree/main) demo if you want to use it in the `README`:
```bash
Output demo.gif

Set Shell "zsh"
Set Padding 16
Set Theme "Monokai Soda"
Set FontFamily "Fira Code"
Set FontSize 26
Set Width 1200
Set Height 550

Env PROMPT "¥ "

# dependencies
Require convert
Require catimg

Type "./marker_generator.py -d 4x4_50 --margin=0 --id=8"

Enter

# Pause for dramatic effect...
Sleep 2000ms

Type@5ms "convert 4x4_50_8.{svg,png}"
Enter

Sleep 1000ms
Type@5ms "catimg -w 36 4x4_50_8.png"
Enter

Type@200ms "easy ArUco!"

# admire output
Sleep 8s
```
which generates:
![Image](https://github.com/user-attachments/assets/a10dd632-8366-47cc-9150-61cc68de79c9)

**Comment by gromain** [comment]
Thanks a lot. I'll put that demo in the README.
And thanks for the '-b' input, I indeed forgot a couple!
